# Generated by Django 4.2.7 on 2023-11-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='', verbose_name='Фото категорії')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус продукту',
                'verbose_name_plural': 'Статуси продуктів',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_date', models.DateField(verbose_name='Дата покупки')),
                ('image', models.FileField(upload_to='', verbose_name='Фото продукту')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('seller_rating', models.FloatField(verbose_name='Рейтинг продавця')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання на продукт в Китаї')),
                ('buying_price', models.FloatField(verbose_name='Ціна покупки')),
                ('description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('full_description', models.TextField(blank=True, verbose_name='Повний опис')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категорія')),
                ('status', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.statusproduct', verbose_name='Статус продукту')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['name'],
            },
        ),
    ]
