# Generated by Django 4.2.7 on 2023-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brands_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото бренду'),
        ),
    ]
