# Generated by Django 4.2.7 on 2023-11-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_brands_brand_rename_brands_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
    ]
